### PR TITLE
Auto-sniff for AMD when moduleType is unknown.

### PR DESCRIPTION
**Pull request by unscriptable**
In-progress fix for #45.
- Factored-out the code finder from findRequires and reused it to look for evidence of AMD in a module.
- Look for AMD evidence when module type is unknown when instantiating a module.
- Stop inferring the moduleType when loading metadata since we're inferring in the instantiate Loader hook now.
- Always pick "amd" or "globals" when inferring.

Initial smoke tests look good.  Still needs more unit tests.

### CODE REVIEW

**Comment by unscriptable** [comment]
This code is working pretty well in my tests, atm.  However, the file scanning procedure is extremely inefficient since it matches on every line feed. (doh!)  

Perhaps I should merge this and then follow-up with a better algorithm (and also add code to avoid regular expressions)?

**Comment by KidkArolis** [comment]
sounds good to me

**Comment by KidkArolis** [comment]
I saw your commented out test `should ignore text inside RegExps` so you probably already know, but if there are quotes in a regex (or I suppose other codeTransitionRxs) the matching stops working, e.g. `underscore` from bower is affected by this.

But also - since this is now used in findRequires as well - regexes in source might break detection of requires? Or was that always the case?

**Comment by unscriptable** [comment]
> if there are quotes in a regex (or I suppose other codeTransitionRxs) the matching stops working, e.g. underscore from bower is affected by this. 

Yep. Lodash is way worse than underscore when it comes to regexps and such. :)  I use it for a functional test in cram.js.

I've been meaning to fix RegExps for a while now.  Finally getting around to it. :)

**Comment by unscriptable** [comment]
Ok, I added code to avoid false-positives inside RegExps.  It's hard to test every variation of source code that could be thrown at this, but the code could certainly use more tests than I've written.  Seems good for now?

**Comment by unscriptable** [comment]
> No longer fails to find the end of a blank string.

LOL. Love that commit message.

Ok, I now have this correctly finding the module type when loading the first module of bootstrap, aerogear-pipeline, jQuery, fastclick, and lodash.  Yes, even lodash.  :)

**Comment by unscriptable** [comment]
The RegExp to find AMD `define`s is the 7th most expensive operation at about 8ms on my tiny project according to Chrome's profiler.  That's clearly not a scalable solution on a larger project, but it should allow a much better experience during the bootstrapping phase of app dev.

**Pull request merged**
